-- AlterTable
ALTER TABLE `users` MODIFY `access_role` ENUM('SUPERADMIN', 'SELLER', 'MEMBERS', 'OTHERS', 'ESTABLISHMENT') NOT NULL DEFAULT 'SELLER';

-- CreateTable
CREATE TABLE `Code_Users` (
    `id` VARCHAR(191) NOT NULL,
    `code` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `userId` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Code_Users` ADD CONSTRAINT `Code_Users_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
